refactoring
WannaCall/wc-country-picker pull request #1
Opened 2024-12-04 20:36 UTC by surajkumar

2024-12-05 04:03 UTC, Taz03 requested changes

2024-12-05 06:31 UTC, surajkumar commented on countrypicker/src/commonMain/kotlin/com/wannacall/countrypicker/viewmodel/CountryPickerViewModel.kt
>      }
I was worried about older, slower devices. Some old phones struggle with a lot of things.

2024-12-05 09:20 UTC, Taz03 commented on countrypicker/src/commonMain/kotlin/com/wannacall/countrypicker/viewmodel/CountryPickerViewModel.kt
>      }
for any device it is a very small list

2024-12-05 15:59 UTC, surajkumar commented on countrypicker/src/commonMain/kotlin/com/wannacall/countrypicker/viewmodel/CountryPickerViewModel.kt
>      }
Fine okay, let's collect some perf scores in the future

2024-12-05 17:53 UTC, Taz03 requested changes

2024-12-05 17:53 UTC, Taz03 commented on countrypicker/src/commonMain/kotlin/com/wannacall/countrypicker/CountryPicker.kt
> +            isError = viewModel.countries.isEmpty() && !isSearchEmpty,
just checking `countries.isEmpty()` is enough since its a predefined list

2024-12-05 17:53 UTC, Taz03 commented on countrypicker/src/commonMain/kotlin/com/wannacall/countrypicker/CountryPicker.kt
> +        isSearchEmpty = viewModel.searchQuery.isEmpty()
why not do this in the mutable state constructor

2024-12-05 17:53 UTC, Taz03 commented on countrypicker/src/commonMain/kotlin/com/wannacall/countrypicker/CountryPickerIcon.kt
> +private const val description = "Open country picker";
caps name?
also make it internal not private

2024-12-05 17:53 UTC, Taz03 commented on countrypicker/src/commonMain/kotlin/com/wannacall/countrypicker/viewmodel/CountryPickerViewModel.kt
> +            countries = filteredCountries
i dont like how its doing too much

2024-12-05 18:39 UTC, surajkumar commented on countrypicker/src/commonMain/kotlin/com/wannacall/countrypicker/viewmodel/CountryPickerViewModel.kt
> +            countries = filteredCountries
it's to stop re-query if the query hasn't changed, if you meant the if?

2024-12-09 14:31 UTC, Taz03 approved these changes

2024-12-09 18:59 UTC, merged